exp_name: ???
exp_type: ???
run_name: null
base_dir: .

gpus: -1
jobid: null
seed: null
debug: false
use_float64: false
float32_matmul_precision: highest

weightquant:
 use: false
 bits: 0
 quantizer: lsbq

 prox_map: parq
 start_step: 0
 final_hard_steps: 0
 steepness: 100

 inout: false
 attn: true
 mlp: true
 framesnet: false

 warmup_steps: 0
 quant_period: 10
 quant_per_channel: false
 quant_shrink: false
 anneal_wd_frac: 0.0
 nm_gamma: 0.0

inputquant:
 use: false
 bits: 8
 quantizer: int
 quant_per_channel: false
 match_weightquant: true

 static:
   use: false
   method: ema
   beta: 0.999
   quantile: 1e-3
   observer_start: 10000
   observer_stop: -1

 mlp: true
 attn: true
 framesnet: true

warm_start_idx: null
save: true
use_mlflow: false
save_source: true
ema: false
ema_decay: 0.999

train: true
evaluate: true
evaluation:
 batchsize: 1024
 eval_quantized: false

plot: true
plotting:
 loss: true

mlflow:
 db: '${base_dir}/runs/${exp_name}/mlflow/mlflow.db'
 artifacts: '${base_dir}/runs/${exp_name}/mlflow/artifacts'

defaults:
 - hydra
 - _self_
